#!/usr/bin/env bash
#
# Generate /srv/vaultkeeper/.env with strong random secrets and patch
# keycloak/realm-export.json to match. Idempotent in the sense that it
# refuses to overwrite an existing .env — delete or move it first.
#
# Run as the admin user from inside /srv/vaultkeeper.

set -euo pipefail

cd /srv/vaultkeeper

if [[ -f .env ]]; then
    echo "[gen-env] .env already exists — refusing to overwrite. Move it aside first." >&2
    exit 1
fi

rand() { openssl rand -base64 48 | tr -d '=+/\n' | cut -c1-"${1:-32}"; }
randhex() { openssl rand -hex "${1:-16}"; }

POSTGRES_PASSWORD="$(rand 40)"
MINIO_ACCESS_KEY="$(randhex 16)"
MINIO_SECRET_KEY="$(rand 48)"
KEYCLOAK_ADMIN_PASSWORD="$(rand 32)"
KEYCLOAK_CLIENT_SECRET_API="$(rand 48)"
KEYCLOAK_CLIENT_SECRET_WEB="$(rand 48)"
NEXTAUTH_SECRET="$(rand 48)"
MEILISEARCH_API_KEY="$(rand 48)"
WITNESS_ENCRYPTION_KEY="$(openssl rand -hex 32)"
MASTER_ENCRYPTION_KEY="$(openssl rand -hex 32)"
BACKUP_ENC_KEY="$(openssl rand -hex 32)"
INSTANCE_ED25519_KEY="$(openssl rand -base64 64 | tr -d '\n')"

# Patch realm-export.json so Keycloak imports matching client secrets.
# Secrets are passed as argv to avoid shell-injection via heredoc interpolation.
python3 - "$KEYCLOAK_CLIENT_SECRET_API" "$KEYCLOAK_CLIENT_SECRET_WEB" <<'PY'
import json, pathlib, sys
secret_api, secret_web = sys.argv[1], sys.argv[2]
p = pathlib.Path('keycloak/realm-export.json')
realm = json.loads(p.read_text())
for c in realm.get('clients', []):
    if c.get('clientId') == 'vaultkeeper-api':
        c['secret'] = secret_api
    elif c.get('clientId') == 'vaultkeeper-web':
        c['secret'] = secret_web
p.write_text(json.dumps(realm, indent=2))
print("[gen-env] patched realm-export.json client secrets")
PY

umask 077
cat > .env <<EOF
# =============================================================================
# VaultKeeper Production Environment
# Generated by gen-env.sh on $(date -u +%FT%TZ)
# DO NOT COMMIT. Back this up somewhere safe.
# =============================================================================

APP_URL=https://vaultkeeper.eu
APP_ENV=production
LOG_LEVEL=info
SERVER_PORT=8080
CORS_ORIGINS=

# --- PostgreSQL ---
POSTGRES_USER=vaultkeeper
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgres://vaultkeeper:${POSTGRES_PASSWORD}@postgres:5432/vaultkeeper?sslmode=require

# --- MinIO ---
MINIO_ENDPOINT=minio:9000
MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
MINIO_BUCKET=evidence
MINIO_USE_SSL=true

# --- Keycloak ---
KEYCLOAK_URL=http://keycloak:8080
KEYCLOAK_REALM=vaultkeeper
KEYCLOAK_CLIENT_ID=vaultkeeper-api
KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET_API}
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}

# --- Next.js ---
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
NEXTAUTH_URL=https://vaultkeeper.eu

# --- TSA (trusted timestamping) ---
TSA_ENABLED=true
TSA_URL=https://timestamp.digicert.com

# --- Meilisearch ---
MEILISEARCH_URL=http://meilisearch:7700
MEILISEARCH_API_KEY=${MEILISEARCH_API_KEY}

# --- Encryption ---
WITNESS_ENCRYPTION_KEY=${WITNESS_ENCRYPTION_KEY}
MASTER_ENCRYPTION_KEY=${MASTER_ENCRYPTION_KEY}
BACKUP_ENC_KEY=${BACKUP_ENC_KEY}
INSTANCE_ED25519_KEY=${INSTANCE_ED25519_KEY}

# --- Limits ---
MAX_CONCURRENT_SESSIONS=3
MAX_UPLOAD_SIZE=10737418240
EOF

chmod 0600 .env
echo "[gen-env] wrote /srv/vaultkeeper/.env (0600, owner=$(stat -c '%U' .env))"
echo "[gen-env] wrote patched keycloak/realm-export.json"

# Emit secrets to stderr for the caller to pipe to a password manager
cat >&2 <<EOF

============ SECRETS (save these) ============
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
KEYCLOAK_CLIENT_SECRET_API=${KEYCLOAK_CLIENT_SECRET_API}
KEYCLOAK_CLIENT_SECRET_WEB=${KEYCLOAK_CLIENT_SECRET_WEB}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
MEILISEARCH_API_KEY=${MEILISEARCH_API_KEY}
WITNESS_ENCRYPTION_KEY=${WITNESS_ENCRYPTION_KEY}
MASTER_ENCRYPTION_KEY=${MASTER_ENCRYPTION_KEY}
BACKUP_ENC_KEY=${BACKUP_ENC_KEY}
INSTANCE_ED25519_KEY=${INSTANCE_ED25519_KEY}
================================================

EOF
